version: '3.5'

services:
  gdn-jenkins:
    container_name: gdn-jenkins
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - /c/Work/Docker/gdn-jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    restart: unless-stopped

    # container_name: gdn-jenkins
    # image: localhost:5000/jenkins-with-docker
    # volumes:
    #   - /c/Work/Docker/gdn-jenkins/jenkins_home:/var/jenkins_home
    #   - /var/run/docker.sock:/var/run/docker.sock
    # ports:
    #   - "8080:8080"
    # restart: unless-stopped

# volumes:
#   - type: bind
#     name: jenkins_home
#     source: /c/Work/Docker/gdn-jenkins/jenkins_home
