//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="xmlns://afsprakenstelsel.medmij.nl/oauthclientlist/release2/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="xmlns://afsprakenstelsel.medmij.nl/oauthclientlist/release2/", IsNullable=false)]
public partial class OAuthclientlist {
    
    private System.DateTime tijdstempelField;
    
    private string volgnummerField;
    
    private OAuthclient[] oAuthclientsField;
    
    /// <remarks/>
    public System.DateTime Tijdstempel {
        get {
            return this.tijdstempelField;
        }
        set {
            this.tijdstempelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string Volgnummer {
        get {
            return this.volgnummerField;
        }
        set {
            this.volgnummerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public OAuthclient[] OAuthclients {
        get {
            return this.oAuthclientsField;
        }
        set {
            this.oAuthclientsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="xmlns://afsprakenstelsel.medmij.nl/oauthclientlist/release2/")]
public partial class OAuthclient {
    
    private string hostnameField;
    
    private string oAuthclientOrganisatienaamField;
    
    /// <remarks/>
    public string Hostname {
        get {
            return this.hostnameField;
        }
        set {
            this.hostnameField = value;
        }
    }
    
    /// <remarks/>
    public string OAuthclientOrganisatienaam {
        get {
            return this.oAuthclientOrganisatienaamField;
        }
        set {
            this.oAuthclientOrganisatienaamField = value;
        }
    }
}
