//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="xmlns://afsprakenstelsel.medmij.nl/zorgaanbiederslijst/release2/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="xmlns://afsprakenstelsel.medmij.nl/zorgaanbiederslijst/release2/", IsNullable=false)]
public partial class Zorgaanbiederslijst {
    
    private System.DateTime tijdstempelField;
    
    private string volgnummerField;
    
    private Zorgaanbieder[] zorgaanbiedersField;
    
    /// <remarks/>
    public System.DateTime Tijdstempel {
        get {
            return this.tijdstempelField;
        }
        set {
            this.tijdstempelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string Volgnummer {
        get {
            return this.volgnummerField;
        }
        set {
            this.volgnummerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Zorgaanbieder[] Zorgaanbieders {
        get {
            return this.zorgaanbiedersField;
        }
        set {
            this.zorgaanbiedersField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="xmlns://afsprakenstelsel.medmij.nl/zorgaanbiederslijst/release2/")]
public partial class Zorgaanbieder {
    
    private string zorgaanbiedernaamField;
    
    private Gegevensdienst[] gegevensdienstenField;
    
    /// <remarks/>
    public string Zorgaanbiedernaam {
        get {
            return this.zorgaanbiedernaamField;
        }
        set {
            this.zorgaanbiedernaamField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Gegevensdienst[] Gegevensdiensten {
        get {
            return this.gegevensdienstenField;
        }
        set {
            this.gegevensdienstenField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="xmlns://afsprakenstelsel.medmij.nl/zorgaanbiederslijst/release2/")]
public partial class Gegevensdienst {
    
    private string gegevensdienstIdField;
    
    private AuthorizationEndpoint authorizationEndpointField;
    
    private TokenEndpoint tokenEndpointField;
    
    private Systeemrol[] systeemrollenField;
    
    /// <remarks/>
    public string GegevensdienstId {
        get {
            return this.gegevensdienstIdField;
        }
        set {
            this.gegevensdienstIdField = value;
        }
    }
    
    /// <remarks/>
    public AuthorizationEndpoint AuthorizationEndpoint {
        get {
            return this.authorizationEndpointField;
        }
        set {
            this.authorizationEndpointField = value;
        }
    }
    
    /// <remarks/>
    public TokenEndpoint TokenEndpoint {
        get {
            return this.tokenEndpointField;
        }
        set {
            this.tokenEndpointField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Systeemrol[] Systeemrollen {
        get {
            return this.systeemrollenField;
        }
        set {
            this.systeemrollenField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="xmlns://afsprakenstelsel.medmij.nl/zorgaanbiederslijst/release2/")]
public partial class AuthorizationEndpoint {
    
    private string authorizationEndpointuriField;
    
    /// <remarks/>
    public string AuthorizationEndpointuri {
        get {
            return this.authorizationEndpointuriField;
        }
        set {
            this.authorizationEndpointuriField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="xmlns://afsprakenstelsel.medmij.nl/zorgaanbiederslijst/release2/")]
public partial class ResourceEndpoint {
    
    private string resourceEndpointuriField;
    
    /// <remarks/>
    public string ResourceEndpointuri {
        get {
            return this.resourceEndpointuriField;
        }
        set {
            this.resourceEndpointuriField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="xmlns://afsprakenstelsel.medmij.nl/zorgaanbiederslijst/release2/")]
public partial class Systeemrol {
    
    private string systeemrolcodeField;
    
    private ResourceEndpoint resourceEndpointField;
    
    /// <remarks/>
    public string Systeemrolcode {
        get {
            return this.systeemrolcodeField;
        }
        set {
            this.systeemrolcodeField = value;
        }
    }
    
    /// <remarks/>
    public ResourceEndpoint ResourceEndpoint {
        get {
            return this.resourceEndpointField;
        }
        set {
            this.resourceEndpointField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="xmlns://afsprakenstelsel.medmij.nl/zorgaanbiederslijst/release2/")]
public partial class TokenEndpoint {
    
    private string tokenEndpointuriField;
    
    /// <remarks/>
    public string TokenEndpointuri {
        get {
            return this.tokenEndpointuriField;
        }
        set {
            this.tokenEndpointuriField = value;
        }
    }
}
